create extension if not exists "pgjwt" with schema "extensions";


create table "public"."date_plan" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "mood_spectrum" text,
    "place" text,
    "food_establishment" text,
    "meeting_time" time with time zone
);


alter table "public"."date_plan" enable row level security;

create table "public"."images" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "image_url" text,
    "event" text,
    "unique_id" uuid not null default gen_random_uuid()
);


alter table "public"."images" enable row level security;

create table "public"."memories" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "description" text default 'null'::text,
    "date" timestamp with time zone default now(),
    "images_id" uuid default gen_random_uuid()
);


alter table "public"."memories" enable row level security;

create table "public"."roadmap" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "image_id" uuid,
    "header" text,
    "body" text,
    "index" bigint default '1'::bigint
);


alter table "public"."roadmap" enable row level security;

CREATE UNIQUE INDEX date_pkey ON public.date_plan USING btree (id);

CREATE UNIQUE INDEX images_pkey ON public.images USING btree (unique_id);

CREATE UNIQUE INDEX memories_pkey ON public.memories USING btree (id);

CREATE UNIQUE INDEX roadmap_pkey ON public.roadmap USING btree (id);

alter table "public"."date_plan" add constraint "date_pkey" PRIMARY KEY using index "date_pkey";

alter table "public"."images" add constraint "images_pkey" PRIMARY KEY using index "images_pkey";

alter table "public"."memories" add constraint "memories_pkey" PRIMARY KEY using index "memories_pkey";

alter table "public"."roadmap" add constraint "roadmap_pkey" PRIMARY KEY using index "roadmap_pkey";

alter table "public"."memories" add constraint "memories_images_id_fkey" FOREIGN KEY (images_id) REFERENCES images(unique_id) not valid;

alter table "public"."memories" validate constraint "memories_images_id_fkey";

alter table "public"."roadmap" add constraint "roadmap_image_id_fkey" FOREIGN KEY (image_id) REFERENCES images(unique_id) not valid;

alter table "public"."roadmap" validate constraint "roadmap_image_id_fkey";

create policy "Enable insert for authenticated users only"
on "public"."date_plan"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."date_plan"
as permissive
for select
to public
using (true);


create policy "Enable read access for authenticed users"
on "public"."images"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for all authenticated users"
on "public"."memories"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for all authenticated users"
on "public"."roadmap"
as permissive
for select
to authenticated
using (true);



